
# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/properties.properties to edit this template


mail.username=flowershop.group6@gmail.com
mail.password=dyjffgcsulhrrxin
mail.host=smtp.gmail.com
mail.port=587